### ISSUE TITLE
Change symbol size?

### ISSUE THREAD

**Issue by Rizhiy** [will8211/unimatrix#8]
It appears that symbol size is not linked to terminal symbols size, is it possible to change it?

**Comment by will8211** [comment]
Could you explain a bit more? Do you mean the width of the characters?  Is it possible that the font you're using has some wider characters? If the emoji are too big, try a different font. I tested it with 'Hack' font.

**Comment by Rizhiy** [comment]
Nvm, it appears my script didn't start the terminal properly.
